title                    : "Pages for GitHub"
title_separator          : "-"
description              : "A nice little test of GitHub Pages"

theme                    : jekyll-theme-cayman
markdown                 : kramdown
